const $=s=>document.querySelector(s);
let state={problems:[],graph:null,selected:null,scale:1,panX:0,panY:0};
async function api(path,options={}){const res=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await res.json();if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const pct=v=>`${Math.round(Number(v||0)*100)}%`;
async function boot(){try{const health=await api('/health');$('#health').textContent=`ONLINE · V${health.version}`;state.problems=(await api('/problems')).problems;renderProblems();await loadMissions();if(state.problems.length)await openProblem(state.problems.at(-1).id)}catch(e){$('#health').textContent='OFFLINE';showError(e)}}
async function loadMissions(){try{const data=await api('/missions');const missions=data.missions||[];$('#mission-dashboard').innerHTML=missions.length?missions.map(m=>`<article class="mission-card"><b>${esc(m.mission_id)}</b><span>${esc(m.status)}</span><p>${esc(m.title)}</p><small>ZERO verdict: ${esc(m.zero_verdict||'none')} · ${esc(m.blocked_reason||m.current_step||'')}</small></article>`).join(''):'<span class="muted">No missions yet. Create one from the console.</span>'}catch(e){$('#mission-dashboard').innerHTML=`<span class="error">Mission dashboard unavailable: ${esc(e.message)}</span>`}}
async function loadSpecialConsoles(){try{const cyber=await api('/cyber/status');$('#cyber-result').innerHTML=`State: <b>${esc(cyber.expert_state)}</b> · Curriculum: ${esc(cyber.curriculum_state)} · Knowledge objects: ${esc(cyber.knowledge_objects)}`}catch(e){$('#cyber-result').innerHTML=`<span class="error">${esc(e.message)}</span>`}try{const gateway=await api('/public-gateway/status');$('#gateway-result').innerHTML=`State: <b>${esc(gateway.state)}</b> · Identity: ${esc(gateway.selected_identity||'none')} · Scans: ${esc(gateway.scan_count||0)}`}catch(e){$('#gateway-result').innerHTML=`<span class="error">${esc(e.message)}</span>`}}
async function runConsole(e){e.preventDefault();const input=$('#console-input').value.trim();if(!input)return;try{const data=await api('/console',{method:'POST',body:JSON.stringify({command:input})});$('#result').innerHTML=`<section class="result-section"><h3>ZERO / OMEGA Command Result</h3><pre>${esc(JSON.stringify(data,null,2))}</pre></section>`;$('#raw-result').textContent=JSON.stringify(data,null,2);$('#raw-panel').classList.remove('hidden');$('#console-input').value='';await loadMissions()}catch(err){showError(err)}}
async function runCyber(e){e.preventDefault();const request=$('#cyber-input').value.trim();if(!request)return;try{const data=await api('/cyber/request',{method:'POST',body:JSON.stringify({request,environment:$('#cyber-env').value})});$('#cyber-result').innerHTML=`<b>${esc(data.classification.request_class)}</b> · ${esc(data.verdict)}<br><small>${esc(data.classification.reason)}</small>`;$('#raw-result').textContent=JSON.stringify(data,null,2);$('#raw-panel').classList.remove('hidden')}catch(err){showError(err)}}
async function runGateway(e){e.preventDefault();const target=$('#gateway-input').value.trim();if(!target)return;try{const data=await api('/public-gateway/scan',{method:'POST',body:JSON.stringify({target})});$('#gateway-result').innerHTML=`<b>${esc(data.verdict)}</b> · ${esc(data.truth_state||'UNVERIFIED')}<br>${(data.findings||[]).map(f=>`<small>${esc(f.id)}: ${esc(f.what)}</small>`).join('<br>')}`;$('#raw-result').textContent=JSON.stringify(data,null,2);$('#raw-panel').classList.remove('hidden')}catch(err){showError(err)}}
function renderProblems(){$('#problem-list').innerHTML=state.problems.map(p=>`<div class="problem ${state.graph?.problem.id===p.id?'active':''}" data-id="${p.id}"><strong>${esc(p.title)}</strong><br><small>${esc(p.description||'No description')}</small></div>`).join('');document.querySelectorAll('.problem').forEach(el=>el.onclick=()=>openProblem(el.dataset.id))}
async function openProblem(id,selectedId=null){state.graph=await api(`/problems/${id}/graph`);state.selected=state.graph.nodes.find(n=>n.id===selectedId)||null;$('#empty').classList.add('hidden');$('#editor').classList.remove('hidden');$('#active-title').textContent=state.graph.problem.title;$('#active-description').textContent=state.graph.problem.description;renderProblems();renderGraph();renderDetail()}
function renderGraph(){const g=$('#graph');g.innerHTML=state.graph.nodes.length?state.graph.nodes.map(n=>`<article class="node ${n.type} ${state.selected?.id===n.id?'selected':''}" data-id="${n.id}"><span class="kind">${esc(n.type)} · ${esc(n.role)}</span><p>${esc(n.statement)}</p><div class="node-meta"><span>${pct(n.confidence)} confidence</span><span>${n.evidence.length} evidence</span></div><div class="meter"><i style="width:${n.confidence*100}%"></i></div></article>`).join(''):'<div class="muted">No nodes yet. Add the first fact, assumption, constraint, or unknown.</div>';document.querySelectorAll('.node').forEach(el=>el.onclick=e=>{e.stopPropagation();selectNode(el.dataset.id)});requestAnimationFrame(drawEdges)}
function drawEdges(){const svg=$('#edges'),canvas=$('#graph-canvas');svg.innerHTML='<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z"/></marker></defs>';const base=canvas.getBoundingClientRect();for(const edge of state.graph.edges){const a=document.querySelector(`.node[data-id="${edge.source_id}"]`),b=document.querySelector(`.node[data-id="${edge.target_id}"]`);if(!a||!b)continue;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),x1=(ar.left+ar.width/2-base.left)/state.scale,y1=(ar.top+ar.height/2-base.top)/state.scale,x2=(br.left+br.width/2-base.left)/state.scale,y2=(br.top+br.height/2-base.top)/state.scale;svg.insertAdjacentHTML('beforeend',`<line class="edge ${edge.type}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" marker-end="url(#arrow)"/><text class="edge-label" x="${(x1+x2)/2}" y="${(y1+y2)/2-5}">${esc(edge.type)}</text>`)}}
function selectNode(id){state.selected=state.graph.nodes.find(n=>n.id===id);renderGraph();renderDetail();$('#edge-panel').classList.remove('hidden');$('#edge-target').innerHTML=state.graph.nodes.filter(n=>n.id!==id).map(n=>`<option value="${n.id}">${esc(n.statement)}</option>`).join('')}
function evidenceRows(n){return n.evidence.length?n.evidence.map(e=>`<li><b>${esc(e.source)}</b><span>${esc(e.note||e.method||e.verification_status||'Recorded source')}</span></li>`).join(''):'<li class="muted">No evidence recorded</li>'}
function renderDetail(){const n=state.selected;if(!n){$('#node-detail').innerHTML='Choose a node in the graph.';$('#edge-panel').classList.add('hidden');return}const edges=state.graph.edges.filter(e=>e.source_id===n.id||e.target_id===n.id);const names=Object.fromEntries(state.graph.nodes.map(x=>[x.id,x.statement]));$('#node-detail').innerHTML=`<form id="edit-node" class="edit-form"><label>Type<select name="type"><option ${n.type==='fact'?'selected':''}>fact</option><option ${n.type==='assumption'?'selected':''}>assumption</option><option ${n.type==='constraint'?'selected':''}>constraint</option><option ${n.type==='unknown'?'selected':''}>unknown</option></select></label><label>Claim<textarea name="statement" required>${esc(n.statement)}</textarea></label><label>Confidence <b>${pct(n.confidence)}</b><input name="confidence" type="range" min="0" max="1" step=".05" value="${n.confidence}"></label><label>Evidence source<input name="source" value="${esc(n.evidence[0]?.source||'')}" placeholder="Source"></label><ul class="evidence-list">${evidenceRows(n)}</ul><label>Assumptions<input name="assumptions" value="${esc(n.assumptions.join('; '))}"></label><label>Uncertainty<input name="uncertainty" value="${esc(n.uncertainty)}"></label><label>Falsification condition<input name="falsifier" value="${esc(n.falsifier)}"></label><div class="form-actions"><button>Save changes</button><button type="button" class="danger" id="delete-node">Delete node</button></div></form><div class="relation-editor"><h4>Relationships</h4>${edges.length?edges.map(e=>`<div><span>${esc(e.source_id===n.id?'→':'←')} ${esc(e.type)} · ${esc(names[e.source_id===n.id?e.target_id:e.source_id])}</span><button class="icon danger delete-edge" data-id="${e.id}">Remove</button></div>`).join(''):'<span class="muted">No relationships</span>'}</div>`;
  $('#edit-node').onsubmit=saveNode;$('#delete-node').onclick=deleteNode;document.querySelectorAll('.delete-edge').forEach(b=>b.onclick=()=>deleteEdge(b.dataset.id))}
async function saveNode(e){e.preventDefault();const f=new FormData(e.target),source=f.get('source').trim(),id=state.selected.id;try{await api(`/nodes/${id}`,{method:'PATCH',body:JSON.stringify({type:f.get('type'),statement:f.get('statement'),confidence:Number(f.get('confidence')),evidence:source?[{source}]:[],assumptions:f.get('assumptions').split(';').map(x=>x.trim()).filter(Boolean),uncertainty:f.get('uncertainty'),falsifier:f.get('falsifier')})});await openProblem(state.graph.problem.id,id)}catch(err){showError(err)}}
async function deleteNode(){const n=state.selected,incident=state.graph.edges.filter(e=>e.source_id===n.id||e.target_id===n.id).length;if(!confirm(`Delete “${n.statement}” and ${incident} connected relationship(s)? This cannot be undone.`))return;try{await api(`/nodes/${n.id}`,{method:'DELETE'});await openProblem(state.graph.problem.id)}catch(err){showError(err)}}
async function deleteEdge(id){if(!confirm('Remove this relationship?'))return;try{await api(`/edges/${id}`,{method:'DELETE'});await openProblem(state.graph.problem.id,state.selected.id)}catch(err){showError(err)}}
$('#new-problem').onclick=()=>$('#problem-form').classList.toggle('hidden');$('#add-node-toggle').onclick=()=>$('#node-form').classList.toggle('hidden');
const claimPrompts={fact:'What has been directly observed or measured?',assumption:'What do you believe must be true?',constraint:'What limit cannot be ignored?',unknown:'What important question is still unanswered?'};
$('#node-form select[name=type]').onchange=e=>{$('#node-form input[name=statement]').placeholder=claimPrompts[e.target.value]};
$('#problem-form').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target),p=await api('/problems',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});state.problems.push(p);e.target.reset();e.target.classList.add('hidden');await openProblem(p.id)}catch(err){showError(err)}};
$('#node-form input[type=range]').oninput=e=>e.target.nextElementSibling.value=Number(e.target.value).toFixed(2);
$('#node-form').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target),source=f.get('source').trim(),payload={type:f.get('type'),statement:f.get('statement'),confidence:Number(f.get('confidence')),evidence:source?[{source}]:[],assumptions:f.get('assumptions').split(';').map(x=>x.trim()).filter(Boolean),uncertainty:f.get('uncertainty'),falsifier:f.get('falsifier')};const node=await api(`/problems/${state.graph.problem.id}/nodes`,{method:'POST',body:JSON.stringify(payload)});e.target.reset();e.target.classList.add('hidden');await openProblem(state.graph.problem.id,node.id)}catch(err){showError(err)}};
$('#add-edge').onclick=async()=>{if(!state.selected)return;try{await api(`/problems/${state.graph.problem.id}/edges`,{method:'POST',body:JSON.stringify({source_id:state.selected.id,target_id:$('#edge-target').value,type:$('#edge-type').value})});await openProblem(state.graph.problem.id,state.selected.id)}catch(err){showError(err)}};
function claimCard(n,label='Claim'){if(!n)return'';return `<article class="result-card ${n.type||''}"><span class="badge">${esc(label)} · ${esc(n.type||'claim')}</span><h4>${esc(n.statement||n.attack||'')}</h4><div class="confidence"><i style="width:${(n.confidence||0)*100}%"></i></div><small>${pct(n.confidence)} confidence · ${n.evidence?.length||0} evidence</small>${n.uncertainty?`<p><b>Uncertainty:</b> ${esc(n.uncertainty)}</p>`:''}${n.falsifier?`<p><b>Falsify when:</b> ${esc(n.falsifier)}</p>`:''}</article>`}
function renderResult(r){let body=`<div class="result-head"><span class="badge operation">${esc(r.operation)}</span><span>Contract ${esc(r.contract_version)}</span></div>`;if(r.operation==='WHY')body+=claimCard(r.target,'Target')+section('Reasons',r.reasons?.map(x=>claimCard(x.node,x.relation)).join(''))+section('Unresolved gaps',r.unresolved_gaps?.map(x=>claimCard(x,'Unknown')).join(''))+section('Challenges',r.challenges?.map(x=>claimCard(x.node||x,'Challenge')).join(''));if(r.operation==='BREAK_IT')body+=section('Attack order',r.attack_order?.map((x,i)=>`<article class="result-card rank"><span class="rank-no">#${i+1}</span>${claimCard(x.node,'Fragility '+pct(x.fragility))}<p>${esc(x.attack)}</p><small>${x.dependents} dependents · evidence strength ${pct(x.evidence_strength)}</small></article>`).join(''));if(r.operation==='PROVE_IT')body+=claimCard(r.target,'Target')+section('Evidence',r.existing_evidence?.length?r.existing_evidence.map(e=>`<div class="evidence-chip">${esc(e.source)} · ${esc(e.verification_status)}</div>`).join(''):'<p class="muted">No evidence yet</p>')+section('Test plan',`<ol>${r.test_plan.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p><b>Pass:</b> ${esc(r.pass_condition)}</p><p><b>Fail:</b> ${esc(r.fail_condition)}</p>`);if(r.operation==='WHAT_IF')body+=claimCard(r.changed,'Changed to '+String(r.hypothetical_truth))+section('Structural impact',r.impacted?.map(x=>claimCard(x.node,x.via)).join(''))+`<p class="notice">${esc(r.note)}</p>`;$('#result').innerHTML=body;$('#raw-result').textContent=JSON.stringify(r,null,2);$('#raw-panel').classList.remove('hidden')}
function section(title,content){return `<section class="result-section"><h3>${esc(title)}</h3>${content||'<p class="muted">None</p>'}</section>`}
document.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=async()=>{if(!state.graph)return;const action=btn.dataset.action;if(action!=='break-it'&&!state.selected)return showError(new Error('Select a node first'));try{const payload=action==='break-it'?{}:{node_id:state.selected.id,...(action==='what-if'?{value:false}:{})};renderResult(await api(`/problems/${state.graph.problem.id}/actions/${action}`,{method:'POST',body:JSON.stringify(payload)}))}catch(err){showError(err)}});
function applyView(){const c=$('#graph-canvas');c.style.transform=`translate(${state.panX}px,${state.panY}px) scale(${state.scale})`;requestAnimationFrame(drawEdges)}
$('#zoom-in').onclick=()=>{state.scale=Math.min(1.8,state.scale+.15);applyView()};$('#zoom-out').onclick=()=>{state.scale=Math.max(.55,state.scale-.15);applyView()};$('#fit-view').onclick=()=>{state.scale=1;state.panX=0;state.panY=0;applyView()};
let drag=null;$('#graph-viewport').onpointerdown=e=>{if(e.target.closest('.node'))return;drag={x:e.clientX,y:e.clientY,px:state.panX,py:state.panY};e.currentTarget.setPointerCapture(e.pointerId)};$('#graph-viewport').onpointermove=e=>{if(!drag)return;state.panX=drag.px+e.clientX-drag.x;state.panY=drag.py+e.clientY-drag.y;applyView()};$('#graph-viewport').onpointerup=()=>drag=null;
function showError(e){$('#result').innerHTML=`<div class="error"><b>Action failed</b><span>${esc(e.message)}</span></div>`}
function finishOnboarding(){localStorage.setItem('omega.onboarding.v1','complete');$('#onboarding').classList.add('hidden')}
$('#create-own').onclick=()=>{finishOnboarding();$('#problem-form').classList.remove('hidden');$('#problem-form input[name=title]').focus()};
$('#use-example').onclick=async()=>{try{const imported=await api('/examples/launch',{method:'POST',body:'{}'});finishOnboarding();state.problems=(await api('/problems')).problems;renderProblems();await openProblem(imported.problem_id)}catch(err){showError(err)}};
$('#export-session').onclick=async()=>{if(!state.selected)return showError(new Error('Select the claim the evaluator should review'));try{const artifact=await api(`/problems/${state.graph.problem.id}/evaluator-session`,{method:'POST',body:JSON.stringify({node_id:state.selected.id})});const blob=new Blob([JSON.stringify(artifact,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='omega-evaluator-session.json';link.click();URL.revokeObjectURL(link.href)}catch(err){showError(err)}};
if(!localStorage.getItem('omega.onboarding.v1'))$('#onboarding').classList.remove('hidden');
$('#console-form').onsubmit=runConsole;
$('#cyber-form').onsubmit=runCyber;
$('#gateway-form').onsubmit=runGateway;
window.addEventListener('resize',()=>requestAnimationFrame(drawEdges));boot();
loadSpecialConsoles();
